name: konnektor
channels:
  - conda-forge
dependencies:
  - python >=3.12
  - pip
  #Test
  - pytest
  - pytest-cov
  - pytest-xdist
  - coverage
  - mypy
  - nbval
  #Typing
  - gufe
  - typing-extensions
  # Sci
  - numpy
  - scipy
  - networkx
  - scikit-learn
  # Chem
  - rdkit
  # docs
  - myst-parser
  - pydata-sphinx-theme

  - pip:
    - dill
    - scikit-mol
