channels:
  - conda-forge
dependencies:
  - kartograf >=1
  - openfe >=0.15
  - itertools >= 3.12
  - pip
  - pip:
    - git+https://github.com/OpenFreeEnergy/openfe-benchmarks.git
    - git+https://github.com/OpenFreeEnergy/konnektor.git
    - scikit-mol
